# Generated by Django 2.2 on 2019-04-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190427_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='goods',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品SPU'),
            preserve_default=False,
        ),
    ]
